name: Monitor Musica Globale
on:
  schedule:
    - cron: '*/30 * * * *' 
  workflow_dispatch: 


# Questa sezione forza l'uso di Node 24 e toglie l'avviso
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Dependencies
        run: pip install requests pandas lxml beautifulsoup4

      - name: Run Monitors
        id: run_scripts
        run: |
          # 1. Eseguiamo iTunes
          echo "Avvio monitor iTunes..."
          OUT_ITUNES=$(python monitor.py)
          echo "Risultato iTunes: $OUT_ITUNES"
          
          # 2. Eseguiamo Spotify
          echo "Avvio monitor Spotify..."
          OUT_SPOTIFY=$(python spotify_monitor.py)
          echo "Risultato Spotify: $OUT_SPOTIFY"
          
          # 3. Controllo risultati per il salvataggio
          if [[ "$OUT_ITUNES" == *"FOUND"* || "$OUT_SPOTIFY" == *"FOUND"* ]]; then
            echo "found=true" >> $GITHUB_OUTPUT
            echo "STATO: Novità rilevate, il file verrà aggiornato."
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "STATO: Nessun cambiamento trovato."
          fi

      - name: Save Changes
        if: steps.run_scripts.outputs.found == 'true'
        run: |
          git config --global user.name 'Bot-Musica'
          git config --global user.email 'actions@github.com'
          git add novita_classifiche.txt
          git commit -m "Aggiornamento automatico: Nuove entrate rilevate"
          git push
          
